# Generated by Django 2.1 on 2018-10-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_price', models.TextField()),
                ('product_old_price', models.TextField()),
                ('product_link', models.TextField()),
                ('product_image', models.TextField()),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Categories', to_field='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site', models.TextField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Websites',
                'db_table': 'website',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='product_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Website', to_field='site', unique=True),
        ),
    ]
